config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions: "admin/sessions",
    invitations: "admin/invitations"
  }

  devise_for :users, controllers: {
    registrations: "registrations", sessions: "sessions", confirmations: "confirmations",
    omniauth_callbacks: "omniauth_callbacks"
  }

  devise_scope :admin do
    get 'admins/sign_out' => "devise/sessions#destroy"
  end

  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
    get "registered", to: "registrations#confirmation_sent"
  end

  #errors
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#rejected"
  get "/500", to: "errors#internal_server_error"

  #public routes
  get "/pages/:page", to: "pages#show"
  resources :contact_email, only: [:create]
  resources :no_city_present, only: [:index]
  root to: "home#index"
  resources :auto_complete, only: [:index]
  resources :cities, only: [:index] do
    put "choose-city", to: "cities#choose_city"
  end
  resources :countries, only: [:index]
  resources :gallery, only: [:index]
  resources :reviews, only: [:index]
  resources :admin_notifications, only: [:create]

  get "presentation", to: "presentation#presentation"

  put "set_language", to: "languages#set_user_language"
  get "filter_cities", to: "locations#filter_cities"

  #authenticated user
  resources :users, only: [:edit, :update] do
    put "change_default_profile", to: "users#change_default_profile"
  end

  namespace :user do
    resources :photo_gallery
    resources :profile, only: [:index]
    resources :messages
    resources :inbox, only: [:index]
    resources :invite_and_share, only: [:index]
    resources :notifications
    resources :reviews, only: [:new, :create, :index]

    resources :quote_requests do
      member do
        put "decline_quote_request", to: "quote_requests#decline_quote_request"
      end
    end

    resources :follows do
      member do
        put "toggle", to: "follows#toggle"
      end
    end

    resources :favourites do
      member do
        put "toggle", to: "favourites#toggle"
      end
    end

    resources :businesses do
      put "claim_business", to: "businesses#claim_business"
    end

    resources :projects do
      get "filter_services", to: "project_steps#filter_services"

      resources :project_business, only: [:show]
      put "shortlist_business", to: "projects#shortlist_business"
      put "accept_quote", to: "projects#accept_quote"
      put "deny_quote", to: "projects#deny_quote"
      put "confirm_completion", to: "projects#confirm_completion"
      put "deny_completion", to: "projects#deny_completion"
      put "cancel_project", to: "projects#cancel_project_by_user"
      put "hide_business", to: "projects#hide_business"
      resources :photo_gallery
      resources :project_steps do
        member do
          put "skip", to: "project_steps#skip"
        end
      end
    end

  end

  namespace :business do
    put :switch_business, to: "switch_business#switch_business"

    resources :stats, only: [:index]
    resources :project_feed, only: [:index, :show]
    resources :inbox, only: [:index]
    resources :profile, only: [:index]
    resources :self_added_projects, only: [:edit, :update]
    resources :businesses, only: [:edit, :update] do
      put "switch_form_section", to: "businesses#switch_form_section"
      put "add_sub_categories", to: "businesses#add_sub_categories"
    end
    resources :favourites, only: [:index, :show]
    resources :user_callbacks, only: [:new, :create]
    resources :quotes do
      put "update_quote_status", to: "quotes#update_quote_status"
      put "download_as_zip", to: "quotes#download_as_zip"
    end
    resources :reviews, only: [:index, :show]
    resources :review_replies
    resources :notifications do
      collection do
        put "mark_as_read", to: "notifications#mark_as_read"
      end
    end
    resources :messages
    resources :projects, only: [:index, :show] do
      put "apply_to_project", to: "projects#apply_to_project"
      put "mark_as_complete", to: "projects#mark_as_complete"
      put "cancel_project", to: "projects#cancel_project_by_business"
      put "hide_project", to: "projects#hide_project"
    end
  end

  namespace :admin do
    root to: "overview#index"

    resources :overview, only: :index

    resource :statistics do
      get 'engagement'
      get 'businesses'
      get 'users'
      get 'categories'
      get 'analytics'
    end

    resource :gallery, only: [] do
      get 'business_banners'
      get 'user_projects'
      get 'business_projects'
      get 'business_logos'
      collection do
        delete 'destroy_video_link/:id', to: 'galleries#destroy_video_link'
        delete 'destroy_business_image/:image/:id', to: 'galleries#destroy_business_image'
        delete 'destroy_attachment/:image/:id', to: 'galleries#destroy_attachment'
        delete 'destroy_banner/:id', to: 'galleries#destroy_banner'
      end
    end

    resources :admin_notifications, only: [:show, :update] do
      collection do
        get 'site', to: 'admin_notifications#site'
        get 'business_claim', to: 'admin_notifications#business_claim'
        get 'inquiries', to: 'admin_notifications#inquiries'
        get 'upgrade', to: 'admin_notifications#upgrade'
        get 'new_businesses', to: 'admin_notifications#new_businesses'
        get 'new_projects', to: 'admin_notifications#new_projects'
        get 'new_reviews', to: 'admin_notifications#new_reviews'
        get 'new_callback_requests', to: 'admin_notifications#new_callback_requests'
      end
      member do
        put 'toggle_resolve'
      end
    end

    resources :admins do
      member do
        put 'enable'
        put 'disable'
      end
    end

    post 'select_country', to: 'base#select_country'

    resources :categories
    resources :sub_categories do
      member do
        put 'enable'
        put 'disable'
      end
    end
    resources :services do
      member do
        put 'enable'
        put 'disable'
      end
    end
    resources :cities do
      member do
        put 'enable'
        put 'disable'
      end
    end
    resources :reviews
    resources :review_replies
    resources :countries do
      member do
        put 'enable'
        put 'disable'
      end
    end

    resources :subscriptions do
      get 'send_invoice'
      get 'send_receipt'
    end

    resources :businesses do
      collection do
        put 'delete_photo', to: 'businesses#delete_photo'
      end

      member do
        put 'enable'
        put 'disable'
        put 'dissociate_owner'
        put 'clear_business_hours'
      end
    end

    resources :vendors do
      resources :subscriptions
      member do
        put 'enable'
        put 'disable'
      end
    end

    resources :users do
      member do
        put 'enable'
        put 'disable'
      end
    end

    resources :projects

    resources :project_types

    resources :verifications
    resources :certifications
    resources :banners, except: :index do
      collection do
        get 'sidebar', to: 'banners#sidebar'
        get 'dashboard', to: 'banners#dashboard'
        get 'listing', to: 'banners#listing'
      end
      put 'enable'
      put 'disable'
    end
  end

  scope path: '(:city)' do
    root to: "home#index"
    resources :self_added_projects, only: [:index]
    resources :businesses do
      put "flag_business", to: "businesses#flag_business"
      collection do
        put "website_view", to: "businesses#website_view"
        put "social_view", to: "businesses#social_view"
        put "number_view", to: "businesses#number_view"
        put "project_view", to: "businesses#project_view"
      end
    end
    resources :listing_map, only: [:index]
    resources :categories, only: [:index, :show]
    resources :sub_categories, only: [:index, :show]
    resources :services, only: [:index, :show]
  end

end

app/models/subscription.rb
class Subscription < ApplicationRecord

  validates :subscription_type, presence: true

  belongs_to :user
  belongs_to :business

  after_create :generate_reference_number

  enum subscription_type: [
    'free',
    'pro',
    'standard',
    'premium'
  ]

  scope :valid, -> { where("expiry_date >= ?", Date.today) }
  scope :new_premium, -> { where(subscription_type: "premium").order(created_at: :desc).includes(user: :businesses) }

  private

  def generate_reference_number
    self.update_attributes(reference_number: "#{ self.business.present? ? self.business.name[0] : self.user.name[0] }#{ Date.today.strftime('%m') }#{ self.id }")
  end

end

app/controllers/admin/subscriptions_controller.rb
class Admin::SubscriptionsController < Admin::BaseController
  before_action :set_subscription, only: [:edit, :update, :destroy]

  def new
    @subscription = Subscription.new

    if params[:user_id].present?
      @target = User.find(params[:user_id])
    elsif params[:business_id].present?
      @target = Business.friendly.find(params[:business_id])
    else
      redirect_back(fallback_location: admin_businesses_path)
    end

    @user_type = params[:user_type]
  end

  def create
    @subscription = Subscription.create(subscription_params)

    @target = subscription_target

    if @subscription.save
      flash[:notice] = "Subscription created"
      send_invoice

      #redirect to vendor or user depending on type
      if @target.is_a?(Business)
        @target.business_upgraded(@subscription)
        redirect_to edit_admin_business_path(@target)
      else
        @target.user_upgraded(@subscription)
        redirect_to edit_admin_user_path(@target)
      end

    else
      flash[:error] = @subscription.errors.full_messages
      render :new
    end
  end

  def edit
    @target = subscription_target
  end

  def update
    @target = subscription_target

    if @subscription.update_attributes(subscription_params)
      flash[:notice] = "Subscription updated"

      #redirect to business or user depending on type
      if @target.is_a?(Business)
        redirect_to edit_admin_business_path(@target)
      else
        redirect_to edit_admin_user_path(@target)
      end

    else
      flash[:error] = @subscription.errors.full_messages
      render :edit
    end
  end

  def destroy
    @target = subscription_target
    @subscription.destroy
    flash[:notice] = "Subscription deleted"

    if @target.is_a?(User)
      redirect_back(fallback_location: edit_admin_user_path(@target.id))
    else
      redirect_back(fallback_location: edit_admin_business_path(@target.id))
    end
  end

  def send_invoice
    @subscription ||= Subscription.find(params[:subscription_id])
    @target = subscription_target
    @contact_email = subscription_email
    @contact_address = subscription_address

    return if @subscription.subscription_type == "free" || @contact_email.blank?

    email = SubscriptionMailer.send_invoice(@subscription, @target, @contact_email, @contact_address).deliver_now

    unless email.errors.present?
      flash[:notice] = "Invoice sent"
    else
      flash[:error] = email.errors
    end

  end

  def send_receipt
    @subscription = Subscription.find(params[:subscription_id])
    @target = subscription_target
    @contact_email = subscription_email
    @contact_address = subscription_address

    return if @subscription.subscription_type == "free" || @contact_email.blank?

    email = SubscriptionMailer.send_receipt(@subscription, @target, @contact_email, @contact_address).deliver_now

    unless email.errors.present?
      flash[:notice] = "Receipt sent"

      respond_to { |format| format.js }

    else
      flash[:error] = email.errors
    end

  end

  protected

  def subscription_target
    #create subscription for user or business
    if @subscription.business.present?
      @subscription.business
    elsif @subscription.user.present?
      @subscription.user
    else
      redirect_back(fallback_location: admin_businesses_path)
    end
  end

  def subscription_email

    if @target.is_a?(User)
      return @target.email
    elsif @target.is_a?(Business) && @target.email.present?
      return @target.email
    elsif @target.is_a?(Business) && @target.user.present?
      return @target.user.email
    end

  end

  def subscription_address

    if @target.is_a?(User) && @target.location.present? && @target.location.street_address.present?
      return @target.location.street_address
    elsif @target.is_a?(Business) && @target.locations.present? && @target.locations.first.street_address.present?
      return @target.locations.first.street_address
    else
      return "Information not provided"
    end

  end

  def set_subscription
    @subscription = Subscription.find(params[:id])
  end

  def subscription_params
    params.require(:subscription).permit(:user_id, :business_id, :subscription_type, :payment_method, :expiry_date, :auto_renew, :amount_paid)
  end

end

app/views/partials/admin/subscriptions/_subscription_form.html.erb
<% if @target.is_a?(User) %>
  <h3><%= link_to 'Users /', admin_users_path,  class: 'u-text-light u-text-regular' %>
  <%= link_to "#{@target.name} / ", edit_admin_user_path(@target),  class: 'u-text-light u-text-regular' %>
  <%= action_name == 'edit' ? @target.name : "New" %> Subscription
  </h3>
<% else %>
  <h3><%= link_to 'Businesses /', admin_businesses_path,  class: 'u-text-light u-text-regular' %>
  <%= link_to "#{@target.name} / ", edit_admin_business_path(@target),  class: 'u-text-light u-text-regular' %>
  <%= action_name == 'edit' ? @target.name : "New" %> Subscription
  </h3>
<% end %>

<div class="grid">
  <div class="grid__col--xs-12 grid__col--md-12">
    <div class="card">


      <%= simple_form_for [:admin, @subscription] do |f| %>
        <% if @target.is_a?(User) %>
          <%= f.input :user_id, input_html: { value: @target.id, class: "u-hide" }, label: false %>
        <% else %>
          <%= f.input :business_id, input_html: { value: @target.id, class: "u-hide" }, label: false %>
        <% end %>
        <%= f.input :user_type, as: :fake, input_html: { value: @user_type, class: "u-hide" }, label: false %>

        <div class="card__section">
          <div class="card__header">
            <h4 class="card__title">Subscription details</h4>
          </div>
          <fieldset class="fieldset">
            <div class="grid">
              <div class="grid__col--xs-12 grid__col--md-6">
                <% if @target.is_a?(Business) %>
                  <%= f.input :subscription_type, wrapper: :text_field, label: "Subscription type", required: true, collection: Subscription.subscription_types.reject{ |option| ["pro"].any?{ |enum_option| enum_option == option } } %>
                <% else %>
                  <%= f.input :subscription_type, wrapper: :text_field, label: "Subscription type", required: true, collection: Subscription.subscription_types.reject{ |option| ["standard", "premium"].any?{ |enum_option| enum_option == option } } %>
                <% end %>
              </div>
              <div class="grid__col--xs-12 grid__col--md-6">
                <%= f.input :payment_method, collection: ["Credit Card", "Wire transfer", "Cash", "Cheque", "Complementary", "Special offer", "Other"], wrapper: :text_field, label: "Payment method", required: true %>
              </div>
              <div class="grid__col--xs-12 grid__col--md-6">
                <%= f.input :amount_paid, wrapper: :text_field, label: "Amount paid", required: true %>
              </div>
              <div class="grid__col--xs-12 grid__col--md-6 grid__col--xlg-6">
                <div class="field">
                  <label class="field__label">* Expiry date</label>
                  <div class="field__input-wrapper">
                    <%= inline_svg("icons/calendar.svg", class: "icon field__add-on field__add-on--right field__add-on--clickthrough field__add-on--clickthrough") %>
                    <%= f.input :expiry_date, wrapper: :date_picker, as: :date_picker_future, placeholder: t("form.date_placeholder") %>
                  </div>
                </div>
              </div>
              <% unless @subscription.new_record? %>
                <div class="grid__col--xs-12 grid__col--md-6">
                  <div class="field">
                    <span class="field__label">Reference #</span>
                    <%= f.input :reference_number, label: false, required: false, disabled: true %>
                  </div>
                </div>
              <% end %>
            </div>
          </fieldset>
        </div>

        <div class="card__section">
          <div class="field">
            <%= f.submit action_name == 'edit' ? 'Save': 'Create', class: 'btn btn--primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>