config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions: "admin/sessions",
    invitations: "admin/invitations"
  }

  devise_for :users, controllers: {
    registrations: "registrations", sessions: "sessions", confirmations: "confirmations",
    omniauth_callbacks: "omniauth_callbacks"
  }

  devise_scope :admin do
    get 'admins/sign_out' => "devise/sessions#destroy"
  end

  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
    get "registered", to: "registrations#confirmation_sent"
  end

  #errors
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#rejected"
  get "/500", to: "errors#internal_server_error"

  #public routes
  get "/pages/:page", to: "pages#show"
  resources :contact_email, only: [:create]
  resources :no_city_present, only: [:index]
  root to: "home#index"
  resources :auto_complete, only: [:index]
  resources :cities, only: [:index] do
    put "choose-city", to: "cities#choose_city"
  end
  resources :countries, only: [:index]
  resources :gallery, only: [:index]
  resources :reviews, only: [:index]
  resources :admin_notifications, only: [:create]

  get "presentation", to: "presentation#presentation"

  put "set_language", to: "languages#set_user_language"
  get "filter_cities", to: "locations#filter_cities"

  #authenticated user
  resources :users, only: [:edit, :update] do
    put "change_default_profile", to: "users#change_default_profile"
  end

  namespace :user do
    resources :photo_gallery
    resources :profile, only: [:index]
    resources :messages
    resources :inbox, only: [:index]
    resources :invite_and_share, only: [:index]
    resources :notifications
    resources :reviews, only: [:new, :create, :index]

    resources :quote_requests do
      member do
        put "decline_quote_request", to: "quote_requests#decline_quote_request"
      end
    end

    resources :follows do
      member do
        put "toggle", to: "follows#toggle"
      end
    end

    resources :favourites do
      member do
        put "toggle", to: "favourites#toggle"
      end
    end

    resources :businesses do
      put "claim_business", to: "businesses#claim_business"
    end

    resources :projects do
      get "filter_services", to: "project_steps#filter_services"

      resources :project_business, only: [:show]
      put "shortlist_business", to: "projects#shortlist_business"
      put "accept_quote", to: "projects#accept_quote"
      put "deny_quote", to: "projects#deny_quote"
      put "confirm_completion", to: "projects#confirm_completion"
      put "deny_completion", to: "projects#deny_completion"
      put "cancel_project", to: "projects#cancel_project_by_user"
      put "hide_business", to: "projects#hide_business"
      resources :photo_gallery
      resources :project_steps do
        member do
          put "skip", to: "project_steps#skip"
        end
      end
    end

  end

  namespace :business do
    put :switch_business, to: "switch_business#switch_business"

    resources :stats, only: [:index]
    resources :project_feed, only: [:index, :show]
    resources :inbox, only: [:index]
    resources :profile, only: [:index]
    resources :self_added_projects, only: [:edit, :update]
    resources :businesses, only: [:edit, :update] do
      put "switch_form_section", to: "businesses#switch_form_section"
      put "add_sub_categories", to: "businesses#add_sub_categories"
    end
    resources :favourites, only: [:index, :show]
    resources :user_callbacks, only: [:new, :create]
    resources :quotes do
      put "update_quote_status", to: "quotes#update_quote_status"
      put "download_as_zip", to: "quotes#download_as_zip"
    end
    resources :reviews, only: [:index, :show]
    resources :review_replies
    resources :notifications do
      collection do
        put "mark_as_read", to: "notifications#mark_as_read"
      end
    end
    resources :messages
    resources :projects, only: [:index, :show] do
      put "apply_to_project", to: "projects#apply_to_project"
      put "mark_as_complete", to: "projects#mark_as_complete"
      put "cancel_project", to: "projects#cancel_project_by_business"
      put "hide_project", to: "projects#hide_project"
    end
  end

  namespace :admin do
    root to: "overview#index"

    resources :overview, only: :index

    resource :statistics do
      get 'engagement'
      get 'businesses'
      get 'users'
      get 'categories'
      get 'analytics'
    end

    resource :gallery, only: [] do
      get 'business_banners'
      get 'user_projects'
      get 'business_projects'
      get 'business_logos'
      collection do
        delete 'destroy_video_link/:id', to: 'galleries#destroy_video_link'
        delete 'destroy_business_image/:image/:id', to: 'galleries#destroy_business_image'
        delete 'destroy_attachment/:image/:id', to: 'galleries#destroy_attachment'
        delete 'destroy_banner/:id', to: 'galleries#destroy_banner'
      end
    end

    resources :admin_notifications, only: [:show, :update] do
      collection do
        get 'site', to: 'admin_notifications#site'
        get 'business_claim', to: 'admin_notifications#business_claim'
        get 'inquiries', to: 'admin_notifications#inquiries'
        get 'upgrade', to: 'admin_notifications#upgrade'
        get 'new_businesses', to: 'admin_notifications#new_businesses'
        get 'new_projects', to: 'admin_notifications#new_projects'
        get 'new_reviews', to: 'admin_notifications#new_reviews'
        get 'new_callback_requests', to: 'admin_notifications#new_callback_requests'
      end
      member do
        put 'toggle_resolve'
      end
    end

    resources :admins do
      member do
        put 'enable'
        put 'disable'
      end
    end

    post 'select_country', to: 'base#select_country'

    resources :categories
    resources :sub_categories do
      member do
        put 'enable'
        put 'disable'
      end
    end
    resources :services do
      member do
        put 'enable'
        put 'disable'
      end
    end
    resources :cities do
      member do
        put 'enable'
        put 'disable'
      end
    end
    resources :reviews
    resources :review_replies
    resources :countries do
      member do
        put 'enable'
        put 'disable'
      end
    end

    resources :subscriptions do
      get 'send_invoice'
      get 'send_receipt'
    end

    resources :businesses do
      collection do
        put 'delete_photo', to: 'businesses#delete_photo'
      end

      member do
        put 'enable'
        put 'disable'
        put 'dissociate_owner'
        put 'clear_business_hours'
      end
    end

    resources :vendors do
      resources :subscriptions
      member do
        put 'enable'
        put 'disable'
      end
    end

    resources :users do
      member do
        put 'enable'
        put 'disable'
      end
    end

    resources :projects

    resources :project_types

    resources :verifications
    resources :certifications
    resources :banners, except: :index do
      collection do
        get 'sidebar', to: 'banners#sidebar'
        get 'dashboard', to: 'banners#dashboard'
        get 'listing', to: 'banners#listing'
      end
      put 'enable'
      put 'disable'
    end
  end

  scope path: '(:city)' do
    root to: "home#index"
    resources :self_added_projects, only: [:index]
    resources :businesses do
      put "flag_business", to: "businesses#flag_business"
      collection do
        put "website_view", to: "businesses#website_view"
        put "social_view", to: "businesses#social_view"
        put "number_view", to: "businesses#number_view"
        put "project_view", to: "businesses#project_view"
      end
    end
    resources :listing_map, only: [:index]
    resources :categories, only: [:index, :show]
    resources :sub_categories, only: [:index, :show]
    resources :services, only: [:index, :show]
  end

end

app/controllers/admin/businesses_controller.rb
class Admin::BusinessesController < Admin::BaseController
  include EmailHelper

  before_action :set_business, only: [:destroy, :delete_photo, :enable, :disable, :update, :edit, :dissociate_owner, :clear_business_hours]
  after_action :verify_authorized


  def index
    authorize Business

    respond_to do |format|
      format.html
      format.json { render json: BusinessDatatable.new(view_context) }
    end
  end

  def new
    authorize Business

    @resource = :admin

    @business = Business.new
    @business.build_business_contact
    2.times { @business.hours_of_operation.build }
  end

  def create
    authorize Business

    @business = current_admin.businesses.create(business_params)

    if @business.save
      redirect_to edit_admin_business_path(@business)
    else
      render :new
    end
  end

  def edit
    authorize @business

    @editor = 'admin'

    @categories = Category.includes(sub_categories: :services)

    @countries = Country.enabled.includes(:translations)
    @cities = City.enabled

    begin
      @admin_editor = Admin.find(@business.admin_editor) if @business.admin_editor.present?
    rescue ActiveRecord::RecordNotFound
      @admin_editor = "deleted"
    end

    resolve_notification

    @business.build_business_contact if @business.business_contact.blank?
    @business.team_members.build if @business.team_members.blank?
    @business.locations.build if @business.locations.blank?
    @business.build_brand if @business.brand.blank?

    if @business.hours_of_operation.blank?
      2.times { @business.hours_of_operation.build }
    elsif @business.hours_of_operation.count == 1
      @business.hours_of_operation.build
    end

  end

  def update
    authorize @business

    handle_disable(params[:business][:disabled]) if params[:business].has_key?(:disabled)

    if @business.update_attributes(business_params)
      @business.update_attributes(admin_editor: current_admin.id, admin_edit_date: Time.now)

      redirect_back(fallback_location: edit)
      flash[:notice] = "Business profile updated."
    else
      redirect_back(fallback_location: edit)
      flash[:error] = @business.errors.full_messages
    end
  end

  def handle_disable(disabled)
    # here we check to see if the disabled attribute has changed
    # if it has, and the business is now disabled, send an email notifying them
    #
    disabled = disabled == "0" ? false : true

    return unless disabled != @business.disabled

    return disable if disabled
  end

  def disable
    authorize @business

    @business.update(disabled: true)

    send_business_disabled_email(@business)

    #redirect_back(fallback_location: admin_businesses_path)

    flash[:error] = "Business disabled"
  end

  def enable
    authorize @business

    @business.update(disabled: false)
    redirect_back(fallback_location: admin_businesses_path)

    flash[:notice] = "Business enabled"
  end

  def delete_photo
    authorize @business

    case params[:photo_type]
    when "logo"
      @business.logo = nil
    when "banner"
      @business.banner = nil
    when "contact profile"
      @business.business_contact.profile_image = nil
    end

    @business.save
  end

  def dissociate_owner
    authorize @business

    @business.update(user: nil)
    redirect_back(fallback_location: edit_admin_business_path(@business))
  end

  def clear_business_hours
    authorize @business

    if params[:shift] == "all"
      @business.hours_of_operation.where(week_period: params[:week_period]).destroy_all
    else
      @business.hours_of_operation.where(week_period: params[:week_period]).first.update_attributes("#{ params[:shift] }_start": nil, "#{ params[:shift] }_end": nil )
    end

    redirect_back(fallback_location: admin_businesses_path)
    flash[:notice] = "Business profile updated."
  end

  def destroy
    authorize @business

    @business.destroy
    redirect_to admin_businesses_path
  end

  def resolve_notification
    unresolved_notification = AdminNotification.where(business: @business, resolved: false).first

    unresolved_notification.update(resolved: true) if unresolved_notification.present?
  end

  protected

  def set_business
    @business = Business.friendly.find(params[:id])
  end

  def policy(record)
    Admin::BusinessPolicy.new(current_admin, record)
  end

  def business_params
    params.require(:business).permit(
      *Business.globalize_attribute_names,
      :name,
      :name_en,
      :name_ar,
      :description,
      :business_hours,
      :min_budget,
      :max_budget,
      :nb_projects_completed,
      :business_type,
      :business_class,
      :project_size,
      :service_area,
      :approved,
      :flagged,
      :disabled,
      :po_box,
      :telephone,
      :fax,
      :email,
      :website,
      :number_of_employees,
      :years_of_establishment,
      :number_of_branches,
      :insurance_coverage,
      :legal_status,
      :id,
      :license_number,
      :banner,
      :logo,
      :user_id,
      :residential,
      :commercial,
      :government,
      :project_type_ids => [],
      :brand_attributes => [ :business_ids => [] ],
      :hours_of_operation_attributes => [  *HoursOfOperation.globalize_attribute_names,
                                           :week_period,
                                           :shift_one_start,
                                           :shift_one_end,
                                           :shift_two_start,
                                           :shift_two_end,
                                           :start_day,
                                           :end_day,
                                           :id ],
      :team_members_attributes =>  [ *TeamMember.globalize_attribute_names,
                                     :name,
                                     :role,
                                     :profile_image,
                                     :phone_number,
                                     :email,
                                     :id,
                                     :_destroy ],
      :locations_attributes =>  [ *Location.globalize_attribute_names,
                                  :number,
                                  :city_id,
                                  :street_address,
                                  :location_type,
                                  :description,
                                  :latitude,
                                  :longitude,
                                  :zip,
                                  :po_box,
                                  :id,
                                  :_destroy ],
      :social_links_attributes => [ :facebook,
                                    :twitter,
                                    :instagram,
                                    :youtube,
                                    :google_plus,
                                    :linkedin,
                                    :prequalification,
                                    :id ],
      :business_contact_attributes =>  [ *BusinessContact.globalize_attribute_names,
                                         :name,
                                         :email,
                                         :position,
                                         :profile_image,
                                         :phone_number,
                                         :id ],
      :self_added_projects_attributes => [ *SelfAddedProject.globalize_attribute_names,
                                           :title,
                                           :description,
                                           :video_link,
                                           :image_one,
                                           :image_two,
                                           :image_three,
                                           :id,
                                           :_destroy ],
      service: {},
      services: [],
      service_ids: [],
      services_attributes: [ :id,
                             :name,
                             :sub_category_id],
      :certification_ids => [],
      certifications_attributes: [ :id,
                                   :name,
                                   :logo],
      verification_ids: [],
      :verifications_attributes => [
        :id
      ],
      :users_attributes => [
        :id
      ]
    )
  end
end

app/controllers/business/base_controller.rb
class Business::BaseController < ApplicationController  
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorised
  before_action :authenticate_admin_or_user!, :check_disabled
  layout "business_profile"
  respond_to :html, :json

  private

  def user_not_authorised
    redirect_back(fallback_location: business_profile_index_path) 
  end

  private

  def check_disabled
    if current_user && current_user.disabled
      sign_out current_user
      redirect_to root_path
      flash[:error] = "Account disabled."
    end
  end

end

app/controllers/business/business_contact_controller.rb
class Business::BusinessContactController < Business::BaseController
end

app/controllers/business/reviews_controller.rb
class Business::ReviewsController < Business::BaseController

  def index
    @reviews = current_business.reviews
  end

  def show
    @review = Review.find(params[:id])
  end

end

app/controllers/business/switch_business_controller.rb
class Business::SwitchBusinessController < Business::BaseController

  def switch_business
    session[:business_id] = params[:business]
    redirect_to business_profile_index_path
  end

end

app/views/businesses/index.html.erb
<%= render partial: "partials/meta_tags/businesses", locals: { banner: @current_city.city_image ? @current_city.city_image.image.url(:small) : @current_city.default_city_image, city: @city, count: @unpaginated_businesses.count } %>

<% content_for :breadcrumbs do %>
  <%= render partial: 'partials/nav/breadcrumb_nav', locals: { breadcrumbs: [], current_breadcrumb: { name: "Businesses", count: @unpaginated_businesses.count } } %>
<% end %>

<section class="section section--padded section--dark u-cover u-text-center has-tint" style="background-image: url('<%= @current_city.city_image ? @current_city.city_image.image.url(:large) : @current_city.default_city_image %> ');">
  <div class="site-wrap has-tint__content">
    <h1 class="u-text-contrast u-text-shadow">
      <%= business_headline(@current_city, params[:filter_by]) %>
    </h1>
  </div>
</section>

<% if @featured_businesses.present? %>
  <section class="section section--tight section--alt section--border-bottom">
    <div class="site-wrap">
      <h4 class="u-text-center--medium-down"><%= t("phrases.verified_businesses") %></h4>
      <div class="grid grid--v-padded">
        <% @featured_businesses.each do |business| %>
          <div class="grid__col--xs-4 u-hide--medium u-text-center">
            <%= link_to business_path(business) do %>
              <div class="u-inline-block u-relative">
                <%= image_tag(business.logo.url(:listing), size: "80x80", class: "u-rounded u-border") %>
              </div>
            <% end %>
          </div>
          <div class="grid__col--xs-4 grid__col--md-4 u-hide--medium-down">
            <div class="media media--middle">
              <%= link_to business_path(id: business.slug), target: "_blank" do %>
                <%= image_tag(business.logo.url(:listing), class: "u-rounded u-border media__figure", width: "64") %>
              <% end %>
              <div class="media__body u-hide--medium-down">
                <%= link_to business_path(id: business.slug), class: 'u-hover-underline u-text-reset', target: "_blank" do %>
                  <h4 class="mb0"><%= business.name %></h4>
                  <small class="u-text-reset"><%= @current_city.name %> (<%= business.distance_from_user_to_s(@current_coordinates, @current_city)%> km)</small>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
<% end %>



<section class="section section--alt">
  <div class="site-wrap">
    <div class="grid">
      <div class="grid__col--xs-12 grid__col--lg-3">
        <% if current_user %>
          <%= link_to t("main_nav.post_a_project"), new_user_project_path, class: "mb3 btn btn--primary btn--xs-full u-hide--large-down" %>
        <% else %>
          <button data-modal="please-log-in", data-modal-target="project", class="js-open-modal btn btn--primary"><%= t("links.post_project") %></button>
        <% end %>
        <div class="card u-hide--large-down">
          <div class="card__section">
            <div class="card__header">
              <h3 class="card__title"><%= t("phases.choose_category") %></h3>
            </div>
            <aside class="sidebar-menu">
              <% @categories.each do |category| %>
                <%= link_to category.name.capitalize, category_path(id: category.slug, filter_by: params[:filter_by]), class: "h4 u-block sidebar-menu__subheading" %>
              <% end %>
            </aside>
          </div>
        </div>
        <% if @side_banners && @side_banners[0].present? %>
          <div class="u-hide--large-down">
            <%= render partial: "partials/banners/side_banner", locals: { banner: @side_banners[0] } %>
          </div>
          <div class="u-hide--large">
            <%= render partial: "partials/banners/side_banner_mobile", locals: { banner: @side_banners[0] } %>
          </div>
        <% end %>

        <div class="card promo-block u-hide--large-down u-cover" style="background-image: url('<%= image_path('listings/promo.jpg') %>')">
          <div class="card__section promo-block__content">
            <h3 class="u-text-contrast u-text-shadow"><%= t("listing.project_prompt.header") %></h3>
            <p class="u-text-contrast u-text-shadow u-text-muted"><%= t("listing.project_prompt.copy") %></p>
            <% if current_user %>
              <%= link_to t("links.post_project"), new_user_project_path, class: "btn btn--primary" %>
            <% else %>
              <button data-modal="please-log-in", data-modal-target="project", class="js-open-modal btn btn--primary"><%= t("links.post_project") %></button>
            <% end %>
          </div>
        </div>
        <% if @side_banners && @side_banners[1].present? %>
          <div class="u-hide--large-down">
            <%= render partial: "partials/banners/side_banner", locals: { banner: @side_banners[1] } %>
          </div>
        <% end %>
      </div>
      <div class="grid__col--xs-12 grid__col--lg-9">
        <div class="grid grid--middle mb3">
          <div class="grid__col--xs-12 grid__col--md-12 grid__col--lg-8">
            <div class="has-popover u-hide--small">
              <small class="u-block u-hide--small-down mb1"><%= t("listing.sort_by") %></small>
              <%= render partial: "partials/filter_sort/filter_sort_mobile", locals: { filter_terms: @filter_terms, default_term: "Recommended" } %>
            </div>
            <div class="u-hide--small-down">
              <small class="mr2"><%= t("filter_sort.sort_by") %></small>
              <div class="segmented-control">
                <%= render partial: "partials/filter_sort/filter_sort", locals: { filter_terms: @filter_terms, default_term: "Recommended" } %>
              </div>
            </div>
          </div>
          <div class="grid__col--lg-4 u-text-right u-hide--large-down">
            <div class="segmented-control">
              <span class="segmented-control__item active btn btn--secondary"><%= inline_svg("icons/list.svg", class: "icon segmented-control__icon") %><%= t("listing.list") %></span>
              <% if @businesses.present? %>
                <%= link_to listing_map_index_path(businesses: @unpaginated_businesses.pluck(:id), category: @category, sub_category: @sub_category, service: @service, city: @current_city), class: "segmented-control__item btn btn--secondary" do %><%= inline_svg("icons/map.svg", class: "icon segmented-control__icon") %><%= t("listing.map") %><% end %>
              <% else %>
                <span class= "segmented-control__item btn btn--secondary u-clickthrough"><%= inline_svg("icons/map.svg", class: "icon segmented-control__icon") %><%= t("listing.map") %></span>
              <% end %>
            </div>
          </div>
        </div>
        <div class="grid">
          <% if params[:filter_by] == "Recommended" %>
            <% @businesses.each_with_index do |business, index| %>
              <% if !business.verified? && @businesses[index - 1].verified? %>
                <%= render partial: "partials/banners/result_banner" %>
              <% end %>
              <%= render "partials/businesses/business_card", business: business %>
            <% end %>
          <% else %>
            <% @businesses.each_with_index do |business, index| %>
              <% if index == 5 || (@businesses.count <= 5 && business == @businesses.last) %>
                <%= render partial: "partials/banners/result_banner" %>
              <% end %>
              <%= render "partials/businesses/business_card", business: business %>
            <% end %>
          <% end %>
        </div>
        <% if @businesses.total_pages > 1 %>
          <div class="mt1">
            <%= paginate @businesses %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

<section class="section section--tight section--alt section--border-top">
  <div class="site-wrap">
    <% if @featured_businesses.present? %>
      <h4 class="u-text-center--medium-down"><%= t("phrases.verified_businesses") %></h4>
      <div class="grid grid--v-padded mb1">
        <% @featured_businesses.each do |business| %>
          <div class="grid__col--xs-4 u-hide--medium u-text-center">
            <%= link_to business_path(business) do %>
              <div class="u-inline-block u-relative">
                <%= image_tag(business.logo.url(:listing), size: "80x80", class: "u-rounded u-border") %>
              </div>
            <% end %>
          </div>
          <div class="grid__col--xs-4 grid__col--md-4 u-hide--medium-down">
            <div class="media media--middle">
              <%= link_to business_path(id: business.slug) do %>
                <%= image_tag(business.logo.url(:listing), class: "u-rounded u-border media__figure", width: "64") %>
              <% end %>
              <div class="media__body u-hide--medium-down">
                <%= link_to business_path(id: business.slug), class: 'u-hover-underline u-text-reset' do %>
                  <h4 class="mb0"><%= business.name %></h4>
                  <small class="u-text-reset"><%= @current_city.name %> (<%= business.distance_from_user_to_s(@current_coordinates, @current_city)%> km)</small>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

    <div class="grid">
      <% @trending_sub_categories.each do |sub_category| %>
        <div class="grid__col--xs-12 grid__col--sm-4 grid__col--md-6 grid__col--lg-3">
          <%= link_to sub_category_path(id: sub_category), class: "card has-tint has-tint--rounded photo-block u-cover", style: "background-image: url('#{ sub_category.category_metadata.present? ? sub_category.category_metadata.banner.url(:small) : image_path("missing/hero.jpg") }')" do %>
            <div class="photo-block__name has-tint__content">
              <span class="u-text-shadow"><%= sub_category.name %></span><br>
              <small class="u-text-muted u-text-shadow"><%= pluralize(sub_category.active_businesses_in_city(@current_city), t("listing.listings")) %></small>
            </div>
          <% end %>
        </div>
      <% end %>
      <div class="grid__col--xs-12 grid__col--md-6 grid__col--lg-3">
        <div class="photo-block photo-block--no-backdrop card u-text-center u-bg-turquoise">
          <div class="card__section">
            <h4 class="u-text-contrast"><%= t("listing.business_prompt.header") %></h4>
            <% if current_user %>
              <%= link_to t("links.add_business"), new_user_business_path, class: "btn btn--contrast btn--small" %>
            <% else %>
              <%= link_to t("links.add_business"), new_business_path, class: "btn btn--contrast btn--small" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section section--tight section--alt section--border-top u-hide--large">
  <div class="site-wrap">
    <div class="btn-group btn-group--full">
      <% if current_user %>
        <%= link_to t("main_nav.post_a_project"), new_user_project_path, class: "btn-group__item btn btn--primary btn--xs-full" %>
      <% else %>
        <button data-modal="please-log-in", data-modal-target="project", class="js-open-modal btn-group__item btn btn--primary btn--xs-full"><%= t("links.post_project") %></button>
      <% end %>
      <%= link_to categories_path(city: @current_city.slug), class: "btn-group__item btn btn--secondary btn--xs-full" do %><%= t("listing.switch_category") %><% end %>
    </div>
    <% if @side_banners && @side_banners[1].present? %>
      <div class="u-hide--large mt2">
        <%= render partial: "partials/banners/side_banner_mobile", locals: { banner: @side_banners[1] } %>
      </div>
    <% end %>
  </div>
</section>

app/views/businesses/new.html.erb
<%= simple_form_for @business do |f| %>
  <%= render partial: "partials/user/businesses/business_form", locals: { f: f } %>
<% end %>