config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions: "admin/sessions",
    invitations: "admin/invitations"
  }

  devise_for :users, controllers: {
    registrations: "registrations", sessions: "sessions", confirmations: "confirmations",
    omniauth_callbacks: "omniauth_callbacks"
  }

  devise_scope :admin do
    get 'admins/sign_out' => "devise/sessions#destroy"
  end

  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
    get "registered", to: "registrations#confirmation_sent"
  end

  #errors
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#rejected"
  get "/500", to: "errors#internal_server_error"

  #public routes
  get "/pages/:page", to: "pages#show"
  resources :contact_email, only: [:create]
  resources :no_city_present, only: [:index]
  root to: "home#index"
  resources :auto_complete, only: [:index]
  resources :cities, only: [:index] do
    put "choose-city", to: "cities#choose_city"
  end
  resources :countries, only: [:index]
  resources :gallery, only: [:index]
  resources :reviews, only: [:index]
  resources :admin_notifications, only: [:create]

  get "presentation", to: "presentation#presentation"

  put "set_language", to: "languages#set_user_language"
  get "filter_cities", to: "locations#filter_cities"

  #authenticated user
  resources :users, only: [:edit, :update] do
    put "change_default_profile", to: "users#change_default_profile"
  end

  namespace :user do
    resources :photo_gallery
    resources :profile, only: [:index]
    resources :messages
    resources :inbox, only: [:index]
    resources :invite_and_share, only: [:index]
    resources :notifications
    resources :reviews, only: [:new, :create, :index]

    resources :quote_requests do
      member do
        put "decline_quote_request", to: "quote_requests#decline_quote_request"
      end
    end

    resources :follows do
      member do
        put "toggle", to: "follows#toggle"
      end
    end

    resources :favourites do
      member do
        put "toggle", to: "favourites#toggle"
      end
    end

    resources :businesses do
      put "claim_business", to: "businesses#claim_business"
    end

    resources :projects do
      get "filter_services", to: "project_steps#filter_services"

      resources :project_business, only: [:show]
      put "shortlist_business", to: "projects#shortlist_business"
      put "accept_quote", to: "projects#accept_quote"
      put "deny_quote", to: "projects#deny_quote"
      put "confirm_completion", to: "projects#confirm_completion"
      put "deny_completion", to: "projects#deny_completion"
      put "cancel_project", to: "projects#cancel_project_by_user"
      put "hide_business", to: "projects#hide_business"
      resources :photo_gallery
      resources :project_steps do
        member do
          put "skip", to: "project_steps#skip"
        end
      end
    end

  end

  namespace :business do
    put :switch_business, to: "switch_business#switch_business"

    resources :stats, only: [:index]
    resources :project_feed, only: [:index, :show]
    resources :inbox, only: [:index]
    resources :profile, only: [:index]
    resources :self_added_projects, only: [:edit, :update]
    resources :businesses, only: [:edit, :update] do
      put "switch_form_section", to: "businesses#switch_form_section"
      put "add_sub_categories", to: "businesses#add_sub_categories"
    end
    resources :favourites, only: [:index, :show]
    resources :user_callbacks, only: [:new, :create]
    resources :quotes do
      put "update_quote_status", to: "quotes#update_quote_status"
      put "download_as_zip", to: "quotes#download_as_zip"
    end
    resources :reviews, only: [:index, :show]
    resources :review_replies
    resources :notifications do
      collection do
        put "mark_as_read", to: "notifications#mark_as_read"
      end
    end
    resources :messages
    resources :projects, only: [:index, :show] do
      put "apply_to_project", to: "projects#apply_to_project"
      put "mark_as_complete", to: "projects#mark_as_complete"
      put "cancel_project", to: "projects#cancel_project_by_business"
      put "hide_project", to: "projects#hide_project"
    end
  end

  namespace :admin do
    root to: "overview#index"

    resources :overview, only: :index

    resource :statistics do
      get 'engagement'
      get 'businesses'
      get 'users'
      get 'categories'
      get 'analytics'
    end

    resource :gallery, only: [] do
      get 'business_banners'
      get 'user_projects'
      get 'business_projects'
      get 'business_logos'
      collection do
        delete 'destroy_video_link/:id', to: 'galleries#destroy_video_link'
        delete 'destroy_business_image/:image/:id', to: 'galleries#destroy_business_image'
        delete 'destroy_attachment/:image/:id', to: 'galleries#destroy_attachment'
        delete 'destroy_banner/:id', to: 'galleries#destroy_banner'
      end
    end

    resources :admin_notifications, only: [:show, :update] do
      collection do
        get 'site', to: 'admin_notifications#site'
        get 'business_claim', to: 'admin_notifications#business_claim'
        get 'inquiries', to: 'admin_notifications#inquiries'
        get 'upgrade', to: 'admin_notifications#upgrade'
        get 'new_businesses', to: 'admin_notifications#new_businesses'
        get 'new_projects', to: 'admin_notifications#new_projects'
        get 'new_reviews', to: 'admin_notifications#new_reviews'
        get 'new_callback_requests', to: 'admin_notifications#new_callback_requests'
      end
      member do
        put 'toggle_resolve'
      end
    end

    resources :admins do
      member do
        put 'enable'
        put 'disable'
      end
    end

    post 'select_country', to: 'base#select_country'

    resources :categories
    resources :sub_categories do
      member do
        put 'enable'
        put 'disable'
      end
    end
    resources :services do
      member do
        put 'enable'
        put 'disable'
      end
    end
    resources :cities do
      member do
        put 'enable'
        put 'disable'
      end
    end
    resources :reviews
    resources :review_replies
    resources :countries do
      member do
        put 'enable'
        put 'disable'
      end
    end

    resources :subscriptions do
      get 'send_invoice'
      get 'send_receipt'
    end

    resources :businesses do
      collection do
        put 'delete_photo', to: 'businesses#delete_photo'
      end

      member do
        put 'enable'
        put 'disable'
        put 'dissociate_owner'
        put 'clear_business_hours'
      end
    end

    resources :vendors do
      resources :subscriptions
      member do
        put 'enable'
        put 'disable'
      end
    end

    resources :users do
      member do
        put 'enable'
        put 'disable'
      end
    end

    resources :projects

    resources :project_types

    resources :verifications
    resources :certifications
    resources :banners, except: :index do
      collection do
        get 'sidebar', to: 'banners#sidebar'
        get 'dashboard', to: 'banners#dashboard'
        get 'listing', to: 'banners#listing'
      end
      put 'enable'
      put 'disable'
    end
  end

  scope path: '(:city)' do
    root to: "home#index"
    resources :self_added_projects, only: [:index]
    resources :businesses do
      put "flag_business", to: "businesses#flag_business"
      collection do
        put "website_view", to: "businesses#website_view"
        put "social_view", to: "businesses#social_view"
        put "number_view", to: "businesses#number_view"
        put "project_view", to: "businesses#project_view"
      end
    end
    resources :listing_map, only: [:index]
    resources :categories, only: [:index, :show]
    resources :sub_categories, only: [:index, :show]
    resources :services, only: [:index, :show]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include SetupTrendingSection

  before_action :check_path_contains_city

  def index
    @categories = Category.order(created_at: :asc)
    @popular_sub_categories = SubCategory.visible.includes(:category_metadata).popular_by_listing_count(@current_city).first(4)
    @specialist = Category.where(name: "Specialists").first
    @city_image = @current_city.city_image ? @current_city.city_image : ''

    setup_trending_section
  end

  private

  def check_path_contains_city
    return if params[:city].present?
    redirect_to "/#{I18n.with_locale(:en){ @current_city.name } }" if @current_city
  end

end

app/views/home/_trending_section.html.erb
<!-- Latest businesses -->

<% if @new_businesses.present? %>
  <section class="trending-section">
    <div class="trending-heading">
      <div class="u-flex u-flex-middle">
        <h4 class="mb0 u-flex-grow"><%= t("trending_section.added") %></h4>
        <%= link_to t("phrases.view_all"), businesses_path(city: @current_city.slug, filter_by: "Latest"), class: "btn btn--link u-hover-underline" %>
      </div>
    </div>

    <div class="grid grid--v-padded">
      <% @new_businesses.each do |item| %>
        <% next if item.nil? %>
        <%= render partial: "partials/trending_section/new_business", locals: { business: item } %>
      <% end %>
    </div>
  </section>
<% end %>


<!-- Featured businesses -->

<% if @new_premium_businesses.present? %>
  <section class="trending-section">
    <div class="trending-heading">
      <div class="u-flex u-flex-middle">
        <h4 class="mb0 u-flex-grow"><%= t("trending_section.upgraded") %></h4>
        <%= link_to t("phrases.view_all"), businesses_path(city: @current_city.slug, filter_by: 'Verified'), class: "btn btn--link u-hover-underline" %>
      </div>
    </div>

    <div class="grid grid--v-padded">
      <% @new_premium_businesses.each do |item| %>
        <% next if item.nil? %>
        <%= render partial: "partials/trending_section/featured_businesses", locals: { business: item } %>
      <% end %>
    </div>
  </section>
<% end %>


<!-- Projects -->

<% if @new_projects.present? %>
  <section class="trending-section">
    <div class="trending-heading">
      <div class="u-flex u-flex-middle">
        <h4 class="mb0 u-flex-grow"><%= t("trending_section.latest") %></h4>
        <%= link_to t("phrases.view_all"), gallery_index_path, class: "btn btn--link u-hover-underline" %>
      </div>
    </div>

    <div class="grid grid--v-padded">
      <% @new_projects.each do |item| %>
        <% next if item.business.nil? %>
        <%= render partial: "partials/trending_section/new_project", locals: { project: item } %>
      <% end %>
    </div>
  </section>
<% end %>

app/views/home/index.html.erb
<%= render partial: "partials/meta_tags/home", locals: { banner: @city_image.present? ? @city_image.image.url(:small) : @current_city.default_city_image , url: request.original_url } %>

<section class="section section--dark hero u-text-center" style="background-image: url('<%= @city_image.present? ? @city_image.image.url(:large) : @current_city.default_city_image %>')">
  <div class="site-wrap">
    <div class="grid grid--center js-search-field">
      <div class="grid__col--xs-12 grid__col--sm-10 grid__col--md-8 grid__col--lg-8">
        <div class="hero__content">
          <h1 class="hero__title u-text-contrast u-text-shadow mb0"><%= t("home_page.header.head") %></h1>
          <h2 class="mt1 hero__subtitle u-text-contrast u-text-muted u-text-shadow"><%= t("home_page.header.sub_head", current_city: @current_city.name) %> <button class="u-text-inherit u-text-underline js-how-it-works-trigger u-hide--medium-down"><%= t("home_page.header.sub_head_link") %></button></h2>

          <div class="btn-group">
            <% if current_user %>
              <button class="btn btn--primary btn-fixed--medium btn-group__item js-open-modal" data-modal="tell_use_your_needs"><%= t("main_nav.tell_us_what_you_need") %></button>  
            <% else %>
              <button class="btn btn--primary btn-fixed--medium btn-group__item js-open-modal" data-modal="tell_use_your_needs"><%= t("main_nav.tell_us_what_you_need") %></button>  
            <% end %>
          </div>
          </p>
        </div>
      </div>
    </div>
  </div>
  <% if @city_image.present? && @city_image.description.present? %>
    <a href="<%= @city_image.link.present? ? full_path(@city_image.link) : '' %>" class="home-city__tooltip tooltip u-hide--large-down" title="<%= @city_image.description %>" target="_blank">
      <%= inline_svg("icons/info.svg", class: "icon icon--small") %>
    </a>
  <% end %>
</section>

<section class="section">
  <div class="site-wrap">
    <div class="trending-section">
      <div class="grid grid--v-padded">
        <% @categories.first(4).each do |category| %>
          <div class="grid__col--xs-12 grid__col--sm-6 grid__col--md-3 u-text-center">
            <%= link_to category_path(id: category), class: "home-category u-text-center mb2" do %>
              <%= inline_svg("icons/#{ I18n.with_locale(:en){ category.name.downcase } }.svg", class: "icon icon--large icon--dark") %>
              <h3 class="m0"><%= category.name %></h3>
              <p class="u-text-reset"><%= t("home_page.explore.listings_available", listing_count: number_with_delimiter(category.active_businesses_in_city(@current_city), delimiter: ", ")) %></p>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="u-text-center">
        <%= link_to "#{ t('home_page.explore.view_all') } ›", categories_path(city: @current_city.slug), class: "mt2 btn btn--primary" %>
      </div>
    </div>
    <div class="trending-section">
      <div class="trending-heading">
        <div class="u-flex u-flex-middle">
          <h3 class="mb0 u-flex-grow"><%= t("popular.trade_services") %> <%= @current_city.name %> </h3>
        </div>
      </div>
      <% if @popular_sub_categories.present? %>
        <div class="grid grid--padded">
          <% @popular_sub_categories.each do |sub_category| %>
            <div class="grid__col--xs-12 grid__col--sm-6 grid__col--lg-3">
              <%= link_to sub_category_path(id: sub_category), class: "card has-tint has-tint--rounded photo-block u-cover", style: "background-image: url('#{ sub_category.category_metadata.present? ? sub_category.category_metadata.banner.url(:small) : image_path("missing/hero.jpg") }')" do %>
                <div class="photo-block__name has-tint__content">
                  <span class="u-text-shadow"><%= sub_category.name %></span><br>
                  <small class="u-text-muted u-text-shadow"><%= pluralize(sub_category.active_businesses_in_city(@current_city), t("listing.listings")) %></small>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <% if @specialist.present? && @specialist.services.present? %>
      <div class="trending-section">
        <div class="trending-heading">
          <div class="u-flex u-flex-middle">
            <h3 class="mb0 u-flex-grow"><%= @specialist.name.capitalize %> <%= t("popular.services_in") %> <%= @current_city.name %></h3>
            <%= link_to t("phrases.view_all"), category_path(id: @specialist.slug, city: @current_city.slug), class: "btn btn--link u-hover-underline" %>
          </div>
        </div>
        <div class="grid">
          <% @specialist.services.visible.shuffle.first(16).in_groups_of(4) do |service_group| %>
            <div class="grid__col--xs-12 grid__col--sm-6 grid__col--lg-3">
              <% service_group.each do |service| %>
                <% next if service == nil %>
                <%= link_to service.name.capitalize, service_path(id: service, sort_by: "Recommended"), class: "mb1 u-block" %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</section>

<section class="section section--border-top section--alt trending">
  <div class="site-wrap">
    <div class="section-heading">
      <h2 class="mb1"><%= t("home_page.trending.head") %></h2>
      <p><%= t("home_page.trending.sub_head", current_city: @current_city.name) %></p>
    </div>
    <%= render partial: "trending_section" %>
  </div>
</section>

<%= render partial: "partials/cta/add_business" %>

<%= content_for :page_scripts do %>
  <%= javascript_include_tag 'auto_complete.js' %>
<% end %>